trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: DockerCredentails

steps:
- task: Docker@2
  displayName: Login to docker
  inputs:
    command: login
    arguments: -p $(DockerPass) -u $(DockerUser)
- task: Docker@2
  displayName: Build and push blogapi
  inputs:
    command: buildAndPush
    buildContext: .
    Dockerfile: API/Blog.API/Dockerfile
    repository: karooloo/blogapi
- task: Docker@2
  displayName: Logout from docker
  inputs:
    command: logout