trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Login to docker
  inputs:
    command: login
    containerRegistry: "Docker - KK"
- task: Docker@2
  displayName: Build and push blogapi
  inputs:
    command: buildAndPush
    buildContext: .
    Dockerfile: API/Blog.API/Dockerfile
    repository: blogapi
- task: Docker@2
  displayName: Logout from docker
  inputs:
    command: logout