version: '3.3'

volumes:
  dbdata: {}
  
services:
  blog-db:
    image: mysql:8.0.21
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=#{MYSQL_ROOT_PASSWORD}#
      - MYSQL_DATABASE=#{MYSQL_DATABASE}#
      - MYSQL_USER=#{MYSQL_USER}#
      - MYSQL_PASSWORD=#{MYSQL_PASSWORD}#
    networks:
      - backend-net
  blog-api:
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend-net
    image: karooloo/blogapi:latest
    restart: always
    depends_on:
      - blog-db
    environment:
      - ConnectionStrings__SqlDatabase=Server=blog-db;Database=#{MYSQL_DATABASE}#;Uid=#{MYSQL_USER}#;Pwd=#{MYSQL_ROOT_PASSWORD}#;
      - AuthContainer__SecretKey=#{SecretKey}#
      - blog__username=#{blog_username}#
      - blog__password=#{blog_password}#
      - Kestrel__Certificates__Default__Path=#{CertPath}#
      - Kestrel__Certificates__Default__Password=#{CertPassword}#
    volumes:
      - /home/debian/blog/:/https/    

networks:
  backend-net:
    driver: bridge