version: '3.7'

volumes:
  dbdata: {}
  
services:
  blog-db:
    image: mysql:8.0.21
    container_name: mysql
    volumes:
      - /Users/karol/dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=blog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
    networks:
      - backend-net
    ports:
      - "3306:3306"
  blog-api:
    ports:
      - "8000:80"
      - "8001:443"
    networks:
      - backend-net
    image: ${DOCKER_REGISTRY-}blogapi
    restart: always
    build:
      context: .
      dockerfile: ./API/Blog.API/Dockerfile
    environment:
      - ConnectionStrings__SqlDatabase=Server=blog-db; Database=blog; Uid=root; Pwd=toor;
    depends_on:
      - blog-db
  blog-spa:
    build:
      context: ./WEB/Blog.WEB/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
    volumes:
        - "/app/node_modules"
        - "./WEB/Blog.WEB/:/app"
    networks:
      - backend-net
    depends_on: 
      - blog-api

networks:
  backend-net:
    driver: bridge