version: '3.7'

volumes:
  dbdata: {}
  
services:
  blog-db:
    image: mysql:8.0.21
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=blog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
    networks:
      - backend-net
  blog-api:
    ports:
      - "80"
      - "443"
    networks:
      - backend-net
    image: ${DOCKER_REGISTRY-}blogapi
    restart: always
    build:
      context: .
      dockerfile: ./API/Blog.API/Dockerfile
    depends_on:
      - blog-db
  blog-spa:
    build:
      context: ./WEB/Blog.WEB/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
        - "/app/node_modules"
        - "./WEB/Blog.WEB/:/app"
    networks:
      - backend-net
    depends_on: 
      - blog-api

networks:
  backend-net:
    driver: bridge